spring:
  datasource:
    url:
    username :
    password :
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl # hibernate에서 camel case를 자동으로 snake case로 변환하는 문제 해결
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # hibernate에서 camel case를 자동으로 snake case로 변환하는 문제 해결
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    open-in-view: false


  servlet:
    multipart:
      max-file-size: 100MB # ?? ??? ?? ? ??? ?? ??? 100 mb? ??
      max-request-size: 500MB # ?? ??? ?? ? ?? ?? ??? ?? 500 mb? ??

logging:
  level:
    org.hibernate.type: trace
    com.app: debug # todo ??? ??

